### ISSUE TITLE
OperationalError: unable to open database file

### ISSUE THREAD

**Issue by BallTongue0** [favll/pogom#105]
When i run python runserver.py i get this:

`Traceback (most recent call last):
  File "runserver.py", line 66, in <module>
    create_tables()
  File "/Users/niklaswikstrom/Documents/pogom/pogom/pogom/models.py", line 206, in create_tables
    db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3404, in connect
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3661, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3668, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3677, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
peewee.OperationalError: unable to open database file`

I'm really new to this and especially python, I'm sure there's something I've missed...

**Comment by hoeguard** [comment]
Please run `python --version` to ensure you are not currently running above python 2.7.10
