### ISSUE TITLE
Error importing Protobuf

### ISSUE THREAD

**Issue by renatorib** [favll/pogom#121]
I just clonned this repo, installed requirements and:

```
→ python runserver.py -p 6000
Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/home/renato/Projects/pogom/pogom/app.py", line 18, in <module>
    from .scan import ScanMetrics, Scanner
  File "/home/renato/Projects/pogom/pogom/scan.py", line 16, in <module>
    from pgoapi import PGoApi
  File "/home/renato/Projects/pogom/pogom/pgoapi/__init__.py", line 51, in <module>
    from .pgoapi import PGoApi
  File "/home/renato/Projects/pogom/pogom/pgoapi/pgoapi.py", line 38, in <module>
    from .rpc_api import RpcApi
  File "/home/renato/Projects/pogom/pogom/pgoapi/rpc_api.py", line 50, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/home/renato/Projects/pogom/pogom/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database
```

**Comment by lax20attack** [comment]
What version of python?

**Comment by renatorib** [comment]
```
→ python --version
Python 2.7.6
```

**Comment by sunkillerqc** [comment]
Same prob

**Comment by lax20attack** [comment]
What environment are you on? Might need to compile protos yourself.

**Comment by AxonDeV** [comment]
Had the same problem, just fixed it a little bit ago.

First try
`sudo pip install --upgrade protobuf`

if that doesn't work, try
`sudo apt-get remove python-protobuf`

Second one is what got it working for me on my Ubuntu VPS.

**Comment by favll** [comment]
Uninstalling and then reinstalling protobuf via pip seems to resolve the issue.
