### ISSUE TITLE
"log.info('Completed {:5.2f}% of scan.'.format(float(ScanMetrics.STEPS_COMPLETED) / ScanMetrics.NUM_STEPS * 100)) ZeroDivisionError: float division by zero" error

### ISSUE THREAD

**Issue by djv2** [favll/pogom#134]
sometimes when i try to scan a new location i get this error

Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\PoGo\pogom-master\pogom\pgoapi\pgoapi.py", line 227, in run
    callback(response)
  File "C:\PoGo\pogom-master\pogom\scan.py", line 70, in callback
    log.info('Completed {:5.2f}% of scan.'.format(float(ScanMetrics.STEPS_COMPLETED) / ScanMetrics.NUM_STEPS * 100))
ZeroDivisionError: float division by zero

temp fix? restart server
help with perm fix?

**Comment by nborrmann** [comment]
fixed in 6ace4720efb072f1b19fe897b094a4557f99da70
