### ISSUE TITLE
Can't access config outside of loopback

### ISSUE THREAD

**Issue by lax20attack** [favll/pogom#177]
Works fine using 127.0.0.1:port/login, but accessing from outside of that gives the following. Map is working fine.

> [2016-08-09 17:07:54,713] ERROR in app: Exception on /login [POST]
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Python27\lib\site-packages\flask\app.py", line 1642, in full_dispatch_request
>     response = self.make_response(rv)
>   File "C:\Python27\lib\site-packages\flask\app.py", line 1731, in make_response
>     raise ValueError('View function did not return a response')
> ValueError: View function did not return a response
> 2016-08-09 17:07:54,760 [     pgoapi] [   INFO] Attempting login: srv19930809
> 2016-08-09 17:07:54,713 [        app] [  ERROR] Exception on /login [POST]
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Python27\lib\site-packages\flask\app.py", line 1642, in full_dispatch_request
>     response = self.make_response(rv)
>   File "C:\Python27\lib\site-packages\flask\app.py", line 1731, in make_response
>     raise ValueError('View function did not return a response')

**Comment by lax20attack** [comment]
omg wrong password
