### ISSUE TITLE
Need help with wsgiref

### ISSUE THREAD

**Issue by newbiekask** [favll/pogom#192]
## My Issue
Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in c:\users\riza-8109088rb\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements.txt (line 17))
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 18))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\RIZA-8~1\AppData\Local\Temp\pip-build-y0d5x57p\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\RIZA-8~1\AppData\Local\Temp\pip-build-y0d5x57p\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\RIZA-8~1\AppData\Local\Temp\pip-build-y0d5x57p\wsgiref\
...
thanks

**Comment by xtratio** [comment]
See https://teamtreehouse.com/community/why-cant-i-install-wsgiref-in-python-virtual-environment
Problem in Python 3.5.2, wsgiref was already installed.
I removed 'wsgiref' line from requirements.txt.
But now have other problem:
```
  Running setup.py install for xxhash ... error
    Complete output from command c:\users\user\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='
C:\\Users\\USER\\AppData\\Local\\Temp\\pip-build-ukapr_ab\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace
('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\USER\AppData\Local\Temp\pip-rkyer5l8-record\install-record.txt --single-version-exte
rnally-managed --compile:
    running install
    running build
    running build_ext
    building 'xxhash' extension
    error: Unable to find vcvarsall.bat
```

**Comment by xtratio** [comment]
There is no correct version C compiler.
I tried to install [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-in/download/details.aspx?id=44266) and Miscrosoft Visual Studio 2008 Express.
Did not help.

But the problem has been solved:
- Removed Python 3.5.2
- Installed Python 2.7.12
- Returned to the line 'wsgiref' in requirements.txt

**Comment by favll** [comment]
We don't support Python 3 at the moment but we might in the near future.
