### ISSUE TITLE
error: cannot invoke setopt() - no curl handle

### ISSUE THREAD

**Issue by anton101101** [favll/pogom#21]
Hi,

Getting the error below can you help.

Thanks

python runserver.py -u xx -p xx -l 55.846627,-4.423636 -r 5000 -c

2016-07-26 19:41:54,172 [     search] [   INFO] Login successful
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/pogom/pogom/search.py", line 233, in search_loop_async
    search_async(args)
  File "/opt/pogom/pogom/search.py", line 166, in search_async
    api.call_async(callback)
  File "/opt/pogom/pogom/pgoapi/pgoapi.py", line 93, in call_async
    self._rpc.request_async(api_endpoint, self._req_method_list, player_position, callback)
  File "/opt/pogom/pogom/pgoapi/rpc_api.py", line 110, in request_async
    self._success_callback, self._error_callback, bundle=bundle)
  File "/opt/pogom/pogom/pgoapi/parallel_curl.py", line 126, in add_request
    self._download_loop()
  File "/opt/pogom/pogom/pgoapi/parallel_curl.py", line 158, in _download_loop
    self._prepare_handle(curl, item)
  File "/opt/pogom/pogom/pgoapi/parallel_curl.py", line 194, in _prepare_handle
    curl.setopt(key, value)
error: cannot invoke setopt() - no curl handle

**Comment by csutcliff** [comment]
same here, it works (slowly) without "-c"

**Comment by nborrmann** [comment]
Post your OS pls.

**Comment by csutcliff** [comment]
for me it's ubuntu server 16.04.1

**Comment by anton101101** [comment]
Ubuntu 14.04.4

**Comment by ajnachakra** [comment]
Same error.
OS X 10.10.5
curl 7.43.0 (x86_64-apple-darwin14.0) libcurl/7.43.0 SecureTransport zlib/1.2.5

**Comment by nborrmann** [comment]
I can reproduce this on my linux machine. 

It works if you revert back to b007ba02 for now. I'm looking for a fix.

**Comment by nborrmann** [comment]
Fixed in ebd6c663

**Comment by anton101101** [comment]
Yes working now.

Thanks for the project the quick update.

**Comment by ajnachakra** [comment]
Also fixed for OS X 10.10.5. Thank you!
