### ISSUE TITLE
No scans yet 

### ISSUE THREAD

**Issue by kpma1985** [favll/pogom#228]
## Checklist
 - [x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x ] I have checked if this issue already exists (both open and closed issues)
 - [x ] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x ] I'm posting the complete log
 - [ x] I'm using a descriptive title for this issue

## My Issue

My, im using the Dockerfile to start the Deamon.
I got this Exception and the Website tells me No scans yet 

016-08-11 10:00:26,414 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
[2016-08-11 10:02:30,808] ERROR in app: Exception on /stats [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/pogom/app.py", line 210, in stats
    return render_template('stats.html', pokemons=Pokemon.get_stats(), total=count)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/src/app/templates/stats.html", line 55, in top-level template code
    <td class="text-right col-sm-1">{% print '{:4.2g}'.format(pokemon.count / total * 100) %}%</td>
ZeroDivisionError: division by zero
2016-08-11 10:02:30,808 [        app] [  ERROR] Exception on /stats [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/pogom/app.py", line 210, in stats
    return render_template('stats.html', pokemons=Pokemon.get_stats(), total=count)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/src/app/templates/stats.html", line 55, in top-level template code
    <td class="text-right col-sm-1">{% print '{:4.2g}'.format(pokemon.count / total * 100) %}%</td>
ZeroDivisionError: division by zero

**Comment by RvV1979** [comment]
Freshly installed from git, first try and I am getting a very similar error (see log below). 

Webpage states "Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details." 

Was this solved? Anyone know what is going wrong? 

Thanks


2016-08-11 13:57:34,382 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
2016-08-11 13:59:46,699 [        app] [  ERROR] Exception on /stats [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/myusername/Documents/pogom/pogom/app.py", line 210, in stats
    return render_template('stats.html', pokemons=Pokemon.get_stats(), total=count)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/myusername/Documents/pogom/templates/stats.html", line 55, in top-level template code
    <td class="text-right col-sm-1">{% print '{:4.2g}'.format(pokemon.count / total * 100) %}%</td>
ZeroDivisionError: division by zero
