### ISSUE TITLE
Problems with start

### ISSUE THREAD

**Issue by Bizadon** [favll/pogom#275]
## Checklist
 - [x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x ] I have checked if this issue already exists (both open and closed issues)
 - [x ] I am using the most recent version of pogom from the master branch
 - [x ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x ] I'm posting the complete log
 - [x ] I'm using a descriptive title for this issue

## My Issue

I have problems with start using -H and -P:

$ python runserver.py -H "192.168.0.102" -H 72
2016-08-13 14:57:43,135 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
Traceback (most recent call last):
  File "runserver.py", line 76, in <module>
    app.run(threaded=True, debug=args.debug, host=args.host, port=args.port)
  File "C:\Python27\lib\site-packages\flask\app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
    inner()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 656, in inner
    fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 544, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "C:\Python27\lib\SocketServer.py", line 417, in __init__
    self.server_bind()
  File "C:\Python27\lib\BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "C:\Python27\lib\SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno 11004] getaddrinfo failed

**Comment by ghvanderweg** [comment]
You're using -H twice: python runserver.py -H "192.168.0.102" -H 72

Should be: python runserver.py -H "192.168.0.102" -P 72

**Comment by Bizadon** [comment]
@ghvanderweg omg, ty very much, I cant understand how I couldnt saw that....
