### ISSUE TITLE
How do I fix OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'?

### ISSUE THREAD

**Issue by Ecaisse98** [favll/pogom#28]
when i run the 
`python filelocation\runserver.py -u username -p password -l "x, y" -r 10
 pause
`
and it gives me this 

`Traceback (most recent call last):
  File "D:\Programming\Project\Python\pogom-master\runserver.py", line 9, in <mo
dule>
    from pogom.app import Pogom
  File "D:\Programming\Project\Python\pogom-master\pogom\app.py", line 13, in <m
odule>
    from .search import set_cover
  File "D:\Programming\Project\Python\pogom-master\pogom\search.py", line 12, in
 <module>
    from pgoapi import PGoApi
  File "D:\Programming\Project\Python\pogom-master\pogom\pgoapi\__init__.py", li
ne 1, in <module>
    from pgoapi      import *
  File "D:\Programming\Project\Python\pogom-master\pogom\pgoapi\pgoapi.py", line
 34, in <module>
    from auth_google import AuthGoogle
  File "D:\Programming\Project\Python\pogom-master\pogom\pgoapi\auth_google.py",
 line 29, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "D:\Programming\Python\lib\site-packages\gpsoauth\__init__.py", line 4, i
n <module>
    from . import google
  File "D:\Programming\Python\lib\site-packages\gpsoauth\google.py", line 4, in
<module>
    from Cryptodome.PublicKey import RSA
  File "D:\Programming\Python\lib\site-packages\Cryptodome\PublicKey\RSA.py", li
ne 79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "D:\Programming\Python\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73
, in <module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "D:\Programming\Python\lib\site-packages\Cryptodome\IO\_PBES.py", line 44
, in <module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "D:\Programming\Python\lib\site-packages\Cryptodome\Cipher\__init__.py",
line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "D:\Programming\Python\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py",
 line 46, in <module>
    """
  File "D:\Programming\Python\lib\site-packages\Cryptodome\Util\_raw_api.py", li
ne 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'
`

**Comment by favll** [comment]
Are you running 64bit Python?

**Comment by Ecaisse98** [comment]
I tried Installing it but it gives me the same error

**Comment by favll** [comment]
If you switched from 64 bit Python to 32 bit you have to reinstall the requirements by first uninstalling and then installing them again: `pip uninstall -r requirements.txt`
Followed by: `pip install -r requirements.txt`

**Comment by Ecaisse98** [comment]
Thank's I will try it as soon as I can

**Comment by Ecaisse98** [comment]
Thank's favll it works now.

**Comment by akk29** [comment]
Python 2.7
pip install Pycrypto 
pip install Crypto 

then run the script
