### ISSUE TITLE
File "/usr/local/bin/pip", line 9, in <module>    Error Closed

### ISSUE THREAD

**Issue by Teamtyler2** [favll/pogom#311]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
Hi My Name Is Damian i am using the most recent version on pogom i am using Raspbian,Raspberry pi 3, Python Version 1.5.6 i think, i am posting the current log
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

...

**Comment by Teamtyler2** [comment]
@nborrmann

**Comment by Mickey32111** [comment]
Fairly easy to fix if you use Google.

http://bfy.tw/7EVN

**Comment by Teamtyler2** [comment]
@Mickey32111 Thanks So Much
