### ISSUE TITLE
Error executing the server

### ISSUE THREAD

**Issue by AngkorDeNNiS** [favll/pogom#319]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

Hi I'm on CentOS 6.5 64-bit, with Python 2.6.6 and pip 8.1.2. 

I'm currently having trouble executing the server and getting it to run, when I type `python runserver.py`,
I get 

Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/home/pogom/pogom/app.py", line 18, in <module>
    from .scan import ScanMetrics, Scanner
  File "/home/pogom/pogom/scan.py", line 16, in <module>
    from pgoapi import PGoApi
  File "/home/pogom/pogom/pgoapi/__init__.py", line 51, in <module>
    from .pgoapi import PGoApi
  File "/home/pogom/pogom/pgoapi/pgoapi.py", line 38, in <module>
    from .rpc_api import RpcApi
  File "/home/pogom/pogom/pgoapi/rpc_api.py", line 47, in <module>
    from .utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/home/pogom/pogom/pgoapi/utilities.py", line 38, in <module>
    from geopy.geocoders import GoogleV3
  File "/usr/lib/python2.6/site-packages/geopy/__init__.py", line 11, in <module>
    from geopy.point import Point
  File "/usr/lib/python2.6/site-packages/geopy/point.py", line 9, in <module>
    from geopy.format import (
  File "/usr/lib/python2.6/site-packages/geopy/format.py", line 119
    for n, d
      ^
SyntaxError: invalid syntax

Not sure what's going on. I'm kind of a noob to stuff like this as well. Any help would be greatly appreciated. I understand that this error on Windows, would be a C++ python compiler issue, so I'm pretty sure it's a compile error on here too, just not sure how to go about fixing it. Thanks in advance.
...

**Comment by nborrmann** [comment]
Get Python 2.7.10+

**Comment by AngkorDeNNiS** [comment]
So I got Python 2.7.10 and it now gives me this error instead,

Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/home/pogom/pogom/app.py", line 6, in <module>
    from flask import Flask, jsonify, render_template, request, abort, redirect, url_for, make_response
ImportError: No module named flask

Any clue?

**Comment by nborrmann** [comment]
run `pip -V` and `python -V`

**Comment by nborrmann** [comment]
#267

**Comment by AngkorDeNNiS** [comment]
[user1@server pogom]# pip -V
pip 8.1.2 from /usr/lib/python2.6/site-packages (python 2.6)
[user1@server pogom]# python -V
Python 2.6.6

I installed Python 2.7 as an alternative install.

**Comment by nborrmann** [comment]
Then you need to change the pip and python commands to point to the 2.7 install.
