### ISSUE TITLE
ValueError: View function did not return a response

### ISSUE THREAD

**Issue by Mickey32111** [favll/pogom#334]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

After updating to the latest commit, when trying to navigate onto the config.html page via the login page, I get the following error:

`[2016-08-19 18:35:27,569] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
    response = self.make_response(rv)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1731, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2016-08-19 18:35:27,569 [        app] [  ERROR] Exception on /login [POST]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
    response = self.make_response(rv)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1731, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response`

Any advice would be appreicated.

**Comment by Mickey32111** [comment]
Don't worry, I've fixed it. Git did a poo all over it when merging commits.
