### ISSUE TITLE
ValueError: View function did not return a response

### ISSUE THREAD

**Issue by Mickey32111** [favll/pogom#335]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

OS: Mac OS X Sierra Beta
Python version: 2.7.12
Flask version: 0.11.1

After updating to the latest commit, I am unable to navigate to the config page. 

In my browser I get:
`Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application`

On my console I get:
`[2016-08-19 19:02:40,486] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/Library/Python/2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
response = self.make_response(rv)
File "/Library/Python/2.7/site-packages/flask/app.py", line 1731, in make_response
raise ValueError('View function did not return a response')

ValueError: View function did not return a response
2016-08-19 19:02:40,486 [        app] [  ERROR] Exception on /login [POST]
Traceback (most recent call last):
File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/Library/Python/2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
response = self.make_response(rv)
File "/Library/Python/2.7/site-packages/flask/app.py", line 1731, in make_response
raise ValueError('View function did not return a response')
ValueError: View function did not return a response`

Anyone have any suggestions?

Note: I did make a Issue on this before but I closed it prematurely thinking I fixed it. (#334)

**Comment by Mickey32111** [comment]
Oh shit, chrome seemed to remember my password wrong? But I never changed my autofill so I don't see how that could've happened.
