### ISSUE TITLE
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /root/pogom/pogom/libencrypt/libencrypt-linux-x86-64.so)

### ISSUE THREAD

**Issue by Nisc3d** [favll/pogom#382]
My Issue:
OS: Linux vps 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u2 x86_64
Python version: Python 2.7.3
Pip version: I don't know how to check that ( I think i have the latest).

root@vps:~/pogom# python runserver.py -H "0.0.0.0" -P 9999
2016-09-02 12:12:33,109 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/root/pogom/pogom/scan.py", line 114, in run
    self.api.resize_workers(num_workers)
  File "/root/pogom/pogom/pgoapi/pgoapi.py", line 71, in resize_workers
    self.create_workers(num_workers - workers_now)
  File "/root/pogom/pogom/pgoapi/pgoapi.py", line 63, in create_workers
    worker = PGoApiWorker(self._signature_lib_path, self._work_queue, self._auth_queue)
  File "/root/pogom/pogom/pgoapi/pgoapi.py", line 177, in __init__
    self.rpc_api.activate_signature(signature_lib_path)
  File "/root/pogom/pogom/pgoapi/rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /root/pogom/pogom/libencrypt/libencrypt-linux-x86-64.so)

Sorry I'm a noob.

**Comment by Nisc3d** [comment]
Followed the steps from the second answer. Works now.
https://unix.stackexchange.com/questions/85505/need-to-install-glibc-2-14-on-wheezy
