### ISSUE TITLE
Computer crashed, now getting errors and can't populate map

### ISSUE THREAD

**Issue by KSUWildcatFan** [favll/pogom#392]
2016-09-06 15:23:52,856 [       scan] [  ERROR] database disk image is malformed
2016-09-06 15:23:52,857 [       scan] [  ERROR] Unexpected error while parsing response.

I'm running this on OSX so things are a bit weird with the Applications Support folder anyway and I'm a bit confused how to work with all of this since my background is Windows.

I'm also seeing this message:

DatabaseError: database disk image is malformed

What all should I remove so it can recreate files as if I'm running this for the first time?

**Comment by favll** [comment]
Delete pogom.db in your pogom folder

**Comment by KSUWildcatFan** [comment]
@favll I did that, in both the running folder and the applications support folder, and it's still throwing errors when it finds pokemon. 

I tried deleting the applications support/pogo and just install it again from requirements.txt and it just tells me it's already installed. Any idea how I wipe it out and start over? Or is there something ELSE I need to delete to get back in order from my already-installed solution?

**Comment by KSUWildcatFan** [comment]
Amanda-Baylesss-iMac-2:~ emo_flamingo$ python 'downloads/pogom-master/runserver.py' -H "0.0.0.0" -P "5000"
2016-09-06 16:34:43,333 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
[2016-09-06 16:34:46,619] ERROR in app: Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
2016-09-06 16:34:46,619 [        app] [  ERROR] Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
[2016-09-06 16:34:56,618] ERROR in app: Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
2016-09-06 16:34:56,618 [        app] [  ERROR] Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
[2016-09-06 16:35:10,058] ERROR in app: Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
2016-09-06 16:35:10,058 [        app] [  ERROR] Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
[2016-09-06 16:35:18,701] ERROR in app: Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
2016-09-06 16:35:18,701 [        app] [  ERROR] Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
[2016-09-06 16:35:28,953] ERROR in app: Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
2016-09-06 16:35:28,953 [        app] [  ERROR] Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
[2016-09-06 16:35:41,367] ERROR in app: Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed
2016-09-06 16:35:41,367 [        app] [  ERROR] Exception on /map-data [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/app.py", line 171, in map_data
    d['pokemons'] = Pokemon.get_active()
  File "/Users/emo_flamingo/Downloads/pogom-master/pogom/models.py", line 59, in get_active
    for p in query:
  File "/Library/Python/2.7/site-packages/peewee.py", line 2967, in __iter__
    return iter(self.execute())
  File "/Library/Python/2.7/site-packages/peewee.py", line 2960, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Python/2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
DatabaseError: database disk image is malformed

**Comment by KSUWildcatFan** [comment]
So..I'm thinking it's Python that's screwed up, not anything to do with Pogo Map at all. Wonderful..time to figure out how to restore that to factory ;(
