### ISSUE TITLE
Implementing the new api into the Scanner

### ISSUE THREAD

**Issue by Su9m7** [favll/pogom#414]
## Checklist
- [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
- [ ] I have checked if this issue already exists (both open and closed issues)
- [ ] I am using the most recent version of pogom from the master branch
- [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
- [ ] I'm posting the complete log
- [ ] I'm using a descriptive title for this issue
## My Issue

Is there anyway to implement the new api into the pogom scanner? My coding skills aren't high enough to understand the scanner's code or to edit the code.

...

**Comment by smartcuc** [comment]
Good question. Not sure by when the new API will be released, but is PoGoM still under development?

**Comment by n0pad** [comment]
I think so

**Comment by smartcuc** [comment]
Would be great. I like PoGoM, is my favorit app.

**Comment by n0pad** [comment]
Wait it there a app for pogom

**Comment by Paralysing** [comment]
I've integrated the new api from Chrales, but it's kinda buggy atm, will do a PR once I fix most of the bugs.

**Comment by HerrTapper** [comment]
the new api is live, lets hope it gets implemented soon!

**Comment by Brandje** [comment]
yes please, pogom is the best scanner out there

**Comment by Paralysing** [comment]
If you are running on a 64bit version of linux, such as ubuntu, try this: https://github.com/PokeHunterProject/pogom-linux. It isn't using the latest api since no one has 0.45.0 re'd yet.

**Comment by Brandje** [comment]
Thx for that Paralysing, now just need to figure out how to get rid of the rate limited errors

**Comment by Paralysing** [comment]
Already patched for 0.45.0, will apply a few patches that I use on my website to minimize empty responses. I would also recommend using a lot of accounts.

**Comment by Su9m7** [comment]
Paralysing, a Windows version would be very nice. Would that be possible?

**Comment by Paralysing** [comment]
Yes, I'll see what I can do, shouldn't be too hard.

**Comment by Paralysing** [comment]
@Su9m7 Could you try to use https://github.com/PokeHunterProject/pogom-windows?

**Comment by Su9m7** [comment]
Yes, i will check it :)

**Comment by Su9m7** [comment]
Console crashes after starting it. Do I have to install the requirements.txt again or anything else?

**Comment by Paralysing** [comment]
Any specific error messages? Are you on a 64bit version of windows?

**Comment by Su9m7** [comment]
Yes 64bit Windows. Tried it on 2 pc's. Cant read anything on the console, it crashes too fast

**Comment by Paralysing** [comment]
I'll check if there are any issues.

**Comment by Paralysing** [comment]
Added a patch for library path, could you replace the contents of pogom/utils.py with https://github.com/PokeHunterProject/pogom-windows/blob/master/pogom/utils.py or pulling the latest version?

**Comment by Paralysing** [comment]
Also, try running the program in cmd with the command "c:\python27\python.exe runserver.py" instead of double clicking.

**Comment by Paralysing** [comment]
Windows instructions:
1. Pull the latest verson from github
2. Hold shift and right click in the main folder, click "Open command window here"
3. In the command window, type "python runserver.py", if that doesn't work, try "c:\python27\python.exe runserver.py"

**Comment by Su9m7** [comment]
Stuck at this https://picload.org/image/rdppridr/unbenannt.png

**Comment by Paralysing** [comment]
Go to localhost:5000 in a browser and configure the map, the rest is exactly the same as the old pogom.

**Comment by Su9m7** [comment]
Working, thanks a lot, you legend

**Comment by Su9m7** [comment]
btw would it be possible to implement pushbullet notifications? https://github.com/favll/pogom/pull/317

**Comment by Paralysing** [comment]
Should be fine if you want to implement it yourself, that PR doesn't affect the api, so there shouldn't be any conflicts.

**Comment by Su9m7** [comment]
It crashes after the changes, error message says its because of the changes in runserver.py. Do you have any idea how to solve that? :/

**Comment by Paralysing** [comment]
I'll implement it myself and check, might be because that PR is based off a very old version of pogom, but I'll need to test it first.

**Comment by Paralysing** [comment]
I got a running application, but I don't have a pushbullet key, could you try the "pushbullet-test" tree (https://github.com/PokeHunterProject/pogom-windows/tree/pushbullet-test)?

**Comment by Paralysing** [comment]
@Su9m7 Does the "pushbullet-test" branch work?

**Comment by Su9m7** [comment]
Sorry, still testing, propably not

**Comment by Su9m7** [comment]
the pushbullet key is old, creating a new one and i will test it again

**Comment by Paralysing** [comment]
Also, remember to change the "mobilealert = {1,2,3,4,5,6,7,8,9}" in models.py to the actual things you want to be alerted about.

**Comment by Su9m7** [comment]
Working, checked that before and added Pidgey to test. The PB key was too old

**Comment by Su9m7** [comment]
Again, thanks a lot @Paralysing

**Comment by Paralysing** [comment]
No problem.

**Comment by PseudoLL** [comment]
getting nttn but rate limit, new accounts, new key. ideas?

**Comment by Su9m7** [comment]
Softban maybe? Only tested it with 4 Locations and 2 accounts over the night without any problems. How many locations and accounts do u use?

**Comment by MartynTech** [comment]
managed to get this installed but it wont scan. when I click on the map nothing happens, I don't get a pin point.

also it says on the setting page "no scans yet"

Any Ideas?

**Comment by MartynTech** [comment]
for some reason its authenticated but I cant click on the map to start a scan. I don't get the pin point.

any ideas?

**Comment by Paralysing** [comment]
@MartynTech Could you try going to localhost:5000/login?

**Comment by Paralysing** [comment]
Also, there was a banwave earlier in the day, make sure the accounts you use aren't banned.

**Comment by MartynTech** [comment]
I can login to the config page okay.

I only created the accounts with ptc-acc-gen about an hour ago so they shouldn't be banned.

**Comment by Paralysing** [comment]
So your only issue is that when you click on the map, no pin appears?

**Comment by MartynTech** [comment]
yes, no pin appears and no scans take place.

**Comment by Paralysing** [comment]
Could you go to the config.json and try adding {"latitude": (your latitude here), "altitude": 0, "radius": 200, "location": "(your latitude here),-(your longitude here)", "longitude": (your longitude here)} in SCAN_LOCATIONS?

Ex: "SCAN_LOCATIONS": [{"latitude": (your latitude here), "altitude": 0, "radius": 200, "location": "(your latitude here),-(your longitude here)", "longitude": (your longitude here)}]

**Comment by Paralysing** [comment]
Forgot that I kept the "-" in, {"latitude": (your latitude here), "altitude": 0, "radius": 200, "location": "(your latitude here),(your longitude here)", "longitude": (your longitude here)} should work.

**Comment by MartynTech** [comment]
okay, I get a point in my area now however I still cannot move the area to search.

Also I get errors saying that its rate limited. no Pokémon are found either.

**Comment by Paralysing** [comment]
Not sure what's wrong with the point, have you done any modifications? Also can you redownload map.js in the static folder? The rate limits are caused by scanning too fast and having too little accounts. Since pogom was made for scanning fast, you will need a decent amount of accounts to prevent being rate limited.

**Comment by iamburny** [comment]
I greatly improved the rate limit issue by adding the following:

scan.py - Line 84 - time.sleep(1)

This adds a 1 second delay between each scan attempt.  

FYI, I have 26 account scanning a 1km area. Also ensure all accounts have been logged in via the official mobile app and have completed the initial training and chosen a nickname, this all help to look less "bot'y"

**Comment by omlet05** [comment]
How many account do you use? I've got only

>  2016-11-15 17:16:48,078 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?

👎

**Comment by Paralysing** [comment]
Using approximately 100 accounts to scan my city, I'm assuming you're on the 0.45.0 version.

**Comment by MartynTech** [comment]
@Paralysing I have re cloned the repository and still cannot click on the map. any more ideas?

Thanks

**Comment by Paralysing** [comment]
I would probably think there is something wrong with login, I'll try and make a branch which removes login completely.

**Comment by Paralysing** [comment]
Also, try to reinstall requirements.txt with the --upgrade argument.

**Comment by M3G4THEKING** [comment]
@Paralysing i'am tring in w10 but i have all empty scans with last git pogom. can help me?tks

**Comment by Paralysing** [comment]
@m3g4mInD How many accounts are you currently using  and how large of an area are you scanning? Due to niantic's new speed limits, you now need a lot more accounts than previously.

**Comment by M3G4THEKING** [comment]
@Paralysing  i have quit with w10 and i started with ubunut and first try voila all work fine,now i need to understand how avoid the captchas  and thanks for your cool repo xd

**Comment by MartynTech** [comment]
hmmm I have installed on windows and whenever I try to start runserver.py I get the error below. any ideas where I'm going wrong? all requirements are installed correctly, as well as node.js

C:\Users\VM\pogom-windows>python runserver.py
Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "C:\Users\VM\pogom-windows\pogom\app.py", line 18, in <module>
    from .scan import ScanMetrics, Scanner
  File "C:\Users\VM\pogom-windows\pogom\scan.py", line 16, in <module>
    from pgoapi import PGoApi
  File "C:\Users\VM\pogom-windows\pogom\pgoapi__init__.py", line 52, in <module

> ```
> from .pgoapi import PGoApi
> ```
> 
>   File "C:\Users\VM\pogom-windows\pogom\pgoapi\pgoapi.py", line 38, in <module>
>     from .rpc_api import RpcApi
>   File "C:\Users\VM\pogom-windows\pogom\pgoapi\rpc_api.py", line 46, in <module>

```
from .utilities import to_camel_case, get_time, get_format_time_diff, Rand48
```

, long_to_bytes, generate_location_hash_by_seed, generate_location_hash, generat
e_request_hash, f2i
  File "C:\Users\VM\pogom-windows\pogom\pgoapi\utilities.py", line 47, in <modul
e>
    _nhash = ctypes.cdll.LoadLibrary(os.path.join(os.path.dirname(os.path.realpa
th(__file__)), "lib/libniantichash-windows-x86-64.dll"))
  File "C:\Python27\lib\ctypes__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes__init__.py", line 362, in **init**
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by Paralysing** [comment]
Are you on a 64bit version of windows?

**Comment by MartynTech** [comment]
yes 64 bit.

I have managed to get round the issue now, it was a 32bit python build I installed.

I'm still having my original issue now of not being able to click to scan on the map. This is a fresh windows 7 build too.

you mentioned something about bypassing login?

**Comment by Paralysing** [comment]
Sure, I'll give you the instructions after I look through the code.

**Comment by Paralysing** [comment]
@MartynTech Replace the code inside pogom/app.py to https://gist.github.com/Paralysing/5ab3412e56b516381bdf917a3424b2e0

**Comment by MartynTech** [comment]
@Paralysing thanks for that, I have updated and still cannot click on the map though.

**Comment by Paralysing** [comment]
Does the left tab say authenticated?

**Comment by MartynTech** [comment]
yes it does. managed to sort it. it was a damm glitch in IE10!

is there a way to have the map centre on your location if accessing on a phone?

thanks

**Comment by Paralysing** [comment]
You would have to use an https connection for any browser to allow you to center location, slightly complicated since you would need a domain. Try using https://github.com/favll/pogom/pull/146

**Comment by Paralysing** [comment]
Niantic forced updated the client to 0.47.0, as of now, using the scanner is dangerous and may result in account bans.

**Comment by MartynTech** [comment]
ill take a look into 146. I do have a domain that I can setup for https.

and thanks for the heads up. I rushed to stop the server as soon as I saw your message!

**Comment by Paralysing** [comment]
No problem, next time I release an update, a warning will show up whenever the scanner api isn't up to date.

**Comment by Paralysing** [comment]
Working on patching pogom for 0.51, I'm not at my normal setup so development might be slower. Will hopefully be done soon.

**Comment by M3G4THEKING** [comment]
@Paralysing  thank you , you have made a nice job until now and i'am here to test and find bugs :)

**Comment by Paralysing** [comment]
Surprisingly, finished patching in a few hours. Going to finish stability checks and I'll release it.

**Comment by Paralysing** [comment]
For anyone still using pogom, https://github.com/PokeHunterProject/pogom-updated is where the code running on the 0.51 api is hosted. Use the -k argument to enter your hashing key, use -sd to put a delay between getmapobject requests.

**Comment by M3G4THEKING** [comment]
@Paralysing  thanks for you great work, i gonna try today and give you return :)

**Comment by MartynTech** [comment]
I have an API key and installed it. However when I try and scan I get a message saying that a response is received but has no data. any ideas?

**Comment by Paralysing** [comment]
Operating system?

**Comment by MartynTech** [comment]
windows 7

**Comment by Paralysing** [comment]
I'll boot up a w7 laptop and test it.

**Comment by MartynTech** [comment]
thanks

**Comment by Paralysing** [comment]
Found the issue, I pushed my test version without the new libs, I'll update it now.

**Comment by Paralysing** [comment]
Redownload the repo and try again?

**Comment by MartynTech** [comment]
it appears to be working now thanks.

What would a good scan delay be as I have mine set at 30 and its pretty slow with 150 accounts.

**Comment by Paralysing** [comment]
I usually either use 1ms or 0, the hashing server slows everything down due to the latency.

**Comment by Paralysing** [comment]
The delay was mostly to make sure that the requests don't get throttled by the hashing server.

**Comment by Paralysing** [comment]
The delay varies for the amount of accounts and the amount of requests you can make with your key.

**Comment by MartynTech** [comment]
right okay, I have set mine to 5ms and i'll see what happens. it was the 150RPM key I purchased. I'm thinking that was a mistake now and should have gone for the 500.

**Comment by MartynTech** [comment]
how can I add the ability to use current location on the map? I have a domain I could use for SSL

**Comment by Paralysing** [comment]
Setup SSL, the map will automatically geolocate when you allow it to access your locations.

**Comment by MartynTech** [comment]
how do I enable SSL on the map?

**Comment by Paralysing** [comment]
A free option is to use cloudflare ssl or you could buy an ssl certificate, but cloudflare should be enough.

**Comment by MartynTech** [comment]
i have added my domain to cloudflare, do i need to install a certificate or anything into the map?

**Comment by Paralysing** [comment]
No, just need to enable the cloud button on the dns settings and set ssl to flexible in crypto.

**Comment by Paralysing** [comment]
Also, for anyone still using pogom, pull the latest version, BuddyAuth changed the endpoint for hashing, so we had to edit the url we were sending and recieving with.

**Comment by darkeagl** [comment]
@Paralysing thx for the great work. Can you update the readme with the new values -k and -sd so we dont need to search for them.
And wouldnt it be better to switch the conversation to the ongoing repo than still writing here?

**Comment by Paralysing** [comment]
Sure, I'll update the readme, would be great if I could get maintainer on this repo so everything doesn't need to be shifted.

**Comment by darkeagl** [comment]
And if not possible, just shift it and who still wants to use it will follow.
Did you pull the IV and password pulls in your repo or is it the plain one, because I would like those implement if possible for them IV with filter and on/off switch

**Comment by Paralysing** [comment]
The version I released is without any addons, as long as the pull requests don't affect the api too much, they should still be able to be merged manually.
