### ISSUE TITLE
Heroku deployment errors

### ISSUE THREAD

**Issue by bbbenji** [favll/pogom#45]
Unable to simply deploy to Heroku. Is this a limitation of the script or actual errors?

> 2016-07-27T17:50:32.907411+00:00 app[web.1]: Traceback (most recent call last):
2016-07-27T17:50:32.904649+00:00 app[web.1]: 2016-07-27 17:50:32,904 [     search] [   INFO] Login successful
2016-07-27T17:50:32.907409+00:00 app[web.1]: Exception in thread search_thread:
2016-07-27T17:50:32.907416+00:00 app[web.1]:     search_async(args)
2016-07-27T17:50:32.907416+00:00 app[web.1]:   File "/app/pogom/search.py", line 157, in search_async
2016-07-27T17:50:32.907414+00:00 app[web.1]:     self.__target(*self.__args, **self.__kwargs)
2016-07-27T17:50:32.907417+00:00 app[web.1]:     login_if_necessary(args, step_location)
2016-07-27T17:50:32.907415+00:00 app[web.1]:   File "/app/pogom/search.py", line 235, in search_loop_async
2016-07-27T17:50:32.907413+00:00 app[web.1]:     self.run()
2016-07-27T17:50:32.907412+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2016-07-27T17:50:32.907413+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/threading.py", line 754, in run
2016-07-27T17:50:32.907419+00:00 app[web.1]: TypeError: unsupported operand type(s) for /: 'str' and 'int'
2016-07-27T17:50:32.907442+00:00 app[web.1]:
2016-07-27T17:50:32.907418+00:00 app[web.1]:   File "/app/pogom/search.py", line 105, in login_if_necessary
2016-07-27T17:50:32.907418+00:00 app[web.1]:     remaining_time = api._rpc.auth_provider._ticket_expire / 1000 - time.time()

**Comment by favll** [comment]
Heroku IPs have been banned :/
