### ISSUE TITLE
Catch all exceptions during login, and consider them failures

### ISSUE THREAD

**Issue by erorus** [favll/pogom#56]
Current behavior: ConnectionError exception bubbles all the way to top, crashing search process

Expected behavior: All exceptions during login are caught, logged, then considered failures to be retried later.

```
2016-07-28 10:54:43,379 [   auth_ptc] [  ERROR] Server timed out
2016-07-28 10:54:43,383 [     search] [   INFO] Login failed, retrying in 300.00 seconds
2016-07-28 10:59:43,388 [   auth_ptc] [   INFO] Login for: ***
2016-07-28 10:59:53,704 [   auth_ptc] [  ERROR] Server timed out
2016-07-28 10:59:53,706 [     search] [   INFO] Login failed, retrying in 300.00 seconds
2016-07-28 11:04:53,795 [   auth_ptc] [   INFO] Login for: ***
Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "pogom/pogom/search.py", line 235, in search_loop_async
    search_async(args)
  File "pogom/pogom/search.py", line 157, in search_async
    login_if_necessary(args, step_location)
  File "pogom/pogom/search.py", line 109, in login_if_necessary
    login(args, position)
  File "pogom/pogom/search.py", line 92, in login
    while not api.login(args.auth_service, args.username, args.password):
  File "pogom/pogom/pgoapi/pgoapi.py", line 151, in login
    if not self._rpc.auth_provider.login(username, password):
  File "pogom/pogom/pgoapi/auth_ptc.py", line 73, in login
    r1 = self._session.post(self.PTC_LOGIN_URL, data=data, headers=head, timeout=10)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 179, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 671, in generate
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='sso.pokemon.com', port=443): Read timed out.
```

**Comment by favll** [comment]
Login should fail safely in the new pogom version.
