### ISSUE TITLE
KeyError: 'GET_MAP_OBJECTS'

### ISSUE THREAD

**Issue by casper-gh** [favll/pogom#66]
Just pulled new commits, got this error:

```
Traceback (most recent call last):
  File "/root/pogom/pogom/search.py", line 129, in search
    parse_map(response_dict)
  File "/root/pogom/pogom/models.py", line 110, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'GET_MAP_OBJECTS'
2016-07-29 18:12:48,640 [     search] [   INFO] Completed  1.60% of scan.
2016-07-29 18:12:48,956 [     search] [   INFO] Completed  1.62% of scan.
2016-07-29 18:12:49,269 [     search] [   INFO] Completed  1.65% of scan.
2016-07-29 18:12:49,587 [     search] [   INFO] Completed  1.67% of scan.
2016-07-29 18:12:49,849 [     search] [  ERROR] Failed to parse response: {'responses': {}}
```

The command that I used to run:

```
python runserver-fast.py -u user -p pass -l "37.803773, -122.407758" -r 4000 -H 0.0.0.0 -P 5000
```

**Comment by chrishoadley** [comment]
I am running into this same issue.

**Comment by russellg89** [comment]
Same issue

**Comment by moggd** [comment]
Same issue

**Comment by Erasmus354** [comment]
Same problem, doesn't appear to be effecting anything

**Comment by moggd** [comment]
@Erasmus354 That doesn't work.  I tried changing in small increments all the way to 20.0 and still got the same amount of errors

**Comment by chrishoadley** [comment]
@Erasmus354 that seemed to work for me. I have it set to 0.25 with 1000-2000 radius. It's slow, but it works.

**Comment by favll** [comment]
A new pogom version is coming soon, that should fix these problems.

**Comment by favll** [comment]
The new Pogom version includes the Api fix.
