### ISSUE TITLE
threading error when changing location

### ISSUE THREAD

**Issue by szeco** [favll/pogom#73]
In the multiple account branch, this error occurs when Set New Location is done via web ui

`Exception in thread search_thread:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/pmon/mfast/pogom/search.py", line 134, in search_loop
    search(api)
  File "/root/pmon/mfast/pogom/search.py", line 117, in search
    api.empty_queue()
  File "/root/pmon/mfast/pogom/pgoapi/pgoapi.py", line 110, in __getattr__
    raise AttributeError
AttributeError
`

**Comment by szeco** [comment]
also: set new location is only activated after a full scan is completed instead of immediately like in _master_

**Comment by favll** [comment]
Yeah, the feature branch is not ready yet for the master branch yet. We are planning to finish it up, fix bugs, etc. today.

**Comment by favll** [comment]
Fixed in the new pogom version.
